# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'
plugin 'cocoapods-repo-update'

def common
  pod 'Alamofire', '~> 4.8.2'
  pod 'Swinject', '~> 2.6.0'
  pod 'SwinjectAutoregistration', '2.5.0'
  pod 'PromisesSwift', '~> 1.2.8'
	pod 'lottie-ios', '~> 3.0.3'
end

def main
  bond
  common
end

def test
  pod 'Cuckoo', '~> 0.13.0'
  pod 'Nimble', '~> 8.0.1'
  pod 'OHHTTPStubs/Swift', '~> 8.0.0'
end

def bond
  pod 'Bond', '~> 7.4.1'
end

target 'DNA.iOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  main
  # Pods for DNA.iOS

  target 'DNA.iOSTests' do
    inherit! :search_paths
    # Pods for testing
    test
  end

end

target 'DNA.iOS.Core' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  common

  target 'DNA.iOS.CoreTests' do
    inherit! :search_paths
    test
  end
end

target 'DNA.iOS.ViewModels' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  bond
  common

  target 'DNA.iOS.ViewModelsTests' do
    inherit! :search_paths
    # Please do not remove bond. Even though the bond is present in the parent dependency, as soon as we remove it from here tests stop working
    bond
    test
  end
end
